/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "sigs.k8s.io/azuredisk-csi-driver/pkg/apis/azuredisk/v1alpha1"
	scheme "sigs.k8s.io/azuredisk-csi-driver/pkg/apis/client/clientset/versioned/scheme"
)

// AzVolumeOperationsGetter has a method to return a AzVolumeOperationInterface.
// A group's client should implement this interface.
type AzVolumeOperationsGetter interface {
	AzVolumeOperations(namespace string) AzVolumeOperationInterface
}

// AzVolumeOperationInterface has methods to work with AzVolumeOperation resources.
type AzVolumeOperationInterface interface {
	Create(ctx context.Context, azVolumeOperation *v1alpha1.AzVolumeOperation, opts v1.CreateOptions) (*v1alpha1.AzVolumeOperation, error)
	Update(ctx context.Context, azVolumeOperation *v1alpha1.AzVolumeOperation, opts v1.UpdateOptions) (*v1alpha1.AzVolumeOperation, error)
	UpdateStatus(ctx context.Context, azVolumeOperation *v1alpha1.AzVolumeOperation, opts v1.UpdateOptions) (*v1alpha1.AzVolumeOperation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AzVolumeOperation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AzVolumeOperationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzVolumeOperation, err error)
	AzVolumeOperationExpansion
}

// azVolumeOperations implements AzVolumeOperationInterface
type azVolumeOperations struct {
	client rest.Interface
	ns     string
}

// newAzVolumeOperations returns a AzVolumeOperations
func newAzVolumeOperations(c *AzstorV1alpha1Client, namespace string) *azVolumeOperations {
	return &azVolumeOperations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azVolumeOperation, and returns the corresponding azVolumeOperation object, and an error if there is any.
func (c *azVolumeOperations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AzVolumeOperation, err error) {
	result = &v1alpha1.AzVolumeOperation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azvolumeoperations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzVolumeOperations that match those selectors.
func (c *azVolumeOperations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AzVolumeOperationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AzVolumeOperationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azvolumeoperations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azVolumeOperations.
func (c *azVolumeOperations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azvolumeoperations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a azVolumeOperation and creates it.  Returns the server's representation of the azVolumeOperation, and an error, if there is any.
func (c *azVolumeOperations) Create(ctx context.Context, azVolumeOperation *v1alpha1.AzVolumeOperation, opts v1.CreateOptions) (result *v1alpha1.AzVolumeOperation, err error) {
	result = &v1alpha1.AzVolumeOperation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azvolumeoperations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azVolumeOperation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a azVolumeOperation and updates it. Returns the server's representation of the azVolumeOperation, and an error, if there is any.
func (c *azVolumeOperations) Update(ctx context.Context, azVolumeOperation *v1alpha1.AzVolumeOperation, opts v1.UpdateOptions) (result *v1alpha1.AzVolumeOperation, err error) {
	result = &v1alpha1.AzVolumeOperation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azvolumeoperations").
		Name(azVolumeOperation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azVolumeOperation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *azVolumeOperations) UpdateStatus(ctx context.Context, azVolumeOperation *v1alpha1.AzVolumeOperation, opts v1.UpdateOptions) (result *v1alpha1.AzVolumeOperation, err error) {
	result = &v1alpha1.AzVolumeOperation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azvolumeoperations").
		Name(azVolumeOperation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azVolumeOperation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the azVolumeOperation and deletes it. Returns an error if one occurs.
func (c *azVolumeOperations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azvolumeoperations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azVolumeOperations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azvolumeoperations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched azVolumeOperation.
func (c *azVolumeOperations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzVolumeOperation, err error) {
	result = &v1alpha1.AzVolumeOperation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azvolumeoperations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
