/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/azuredisk-csi-driver/pkg/apis/azuredisk/v1alpha1"
)

// FakeAzVolumeOperations implements AzVolumeOperationInterface
type FakeAzVolumeOperations struct {
	Fake *FakeDiskV1alpha1
	ns   string
}

var azvolumeoperationsResource = schema.GroupVersionResource{Group: "disk.csi.azure.com", Version: "v1alpha1", Resource: "azvolumeoperations"}

var azvolumeoperationsKind = schema.GroupVersionKind{Group: "disk.csi.azure.com", Version: "v1alpha1", Kind: "AzVolumeOperation"}

// Get takes name of the azVolumeOperation, and returns the corresponding azVolumeOperation object, and an error if there is any.
func (c *FakeAzVolumeOperations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AzVolumeOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azvolumeoperationsResource, c.ns, name), &v1alpha1.AzVolumeOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzVolumeOperation), err
}

// List takes label and field selectors, and returns the list of AzVolumeOperations that match those selectors.
func (c *FakeAzVolumeOperations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AzVolumeOperationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azvolumeoperationsResource, azvolumeoperationsKind, c.ns, opts), &v1alpha1.AzVolumeOperationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AzVolumeOperationList{ListMeta: obj.(*v1alpha1.AzVolumeOperationList).ListMeta}
	for _, item := range obj.(*v1alpha1.AzVolumeOperationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azVolumeOperations.
func (c *FakeAzVolumeOperations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azvolumeoperationsResource, c.ns, opts))

}

// Create takes the representation of a azVolumeOperation and creates it.  Returns the server's representation of the azVolumeOperation, and an error, if there is any.
func (c *FakeAzVolumeOperations) Create(ctx context.Context, azVolumeOperation *v1alpha1.AzVolumeOperation, opts v1.CreateOptions) (result *v1alpha1.AzVolumeOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azvolumeoperationsResource, c.ns, azVolumeOperation), &v1alpha1.AzVolumeOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzVolumeOperation), err
}

// Update takes the representation of a azVolumeOperation and updates it. Returns the server's representation of the azVolumeOperation, and an error, if there is any.
func (c *FakeAzVolumeOperations) Update(ctx context.Context, azVolumeOperation *v1alpha1.AzVolumeOperation, opts v1.UpdateOptions) (result *v1alpha1.AzVolumeOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azvolumeoperationsResource, c.ns, azVolumeOperation), &v1alpha1.AzVolumeOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzVolumeOperation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAzVolumeOperations) UpdateStatus(ctx context.Context, azVolumeOperation *v1alpha1.AzVolumeOperation, opts v1.UpdateOptions) (*v1alpha1.AzVolumeOperation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(azvolumeoperationsResource, "status", c.ns, azVolumeOperation), &v1alpha1.AzVolumeOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzVolumeOperation), err
}

// Delete takes name of the azVolumeOperation and deletes it. Returns an error if one occurs.
func (c *FakeAzVolumeOperations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(azvolumeoperationsResource, c.ns, name, opts), &v1alpha1.AzVolumeOperation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzVolumeOperations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azvolumeoperationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AzVolumeOperationList{})
	return err
}

// Patch applies the patch and returns the patched azVolumeOperation.
func (c *FakeAzVolumeOperations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzVolumeOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azvolumeoperationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AzVolumeOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzVolumeOperation), err
}
